"""initial schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-07-07

Hand-written (not autogenerated) so the create order and FK handling are explicit and
render correctly on both Postgres and SQLite. Tables are created in dependency order —
projects -> agents -> log_entries -> checkmarks -> shared_context — so no forward FK
reference needs deferring.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from handler.db.types import PortableBigInt, PortableJSON, PortableTimestamp

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

AGENT_STATUSES = "'working', 'paused_for_input', 'blocked', 'done'"
GATE_STATUSES = "'pass', 'fail', 'unknown'"
CI_STATUSES = "'not_applicable', 'pending', 'pass', 'fail'"
VISIBILITIES = "'project', 'global'"


def upgrade() -> None:
    op.create_table(
        "projects",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("root_dir", sa.String(), nullable=False),
        sa.Column("git_remote", sa.String()),
        sa.Column("credential_ref", sa.String()),
        sa.Column("created_at", PortableTimestamp, nullable=False, server_default=sa.func.now()),
    )

    op.create_table(
        "agents",
        sa.Column("id", PortableBigInt, primary_key=True, autoincrement=True),
        sa.Column("project_id", sa.String(), sa.ForeignKey("projects.id"), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("working_dir", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", PortableTimestamp, nullable=False, server_default=sa.func.now()),
        sa.UniqueConstraint("project_id", "name", name="uq_agents_project_name"),
        sa.CheckConstraint(f"status IN ({AGENT_STATUSES})", name="ck_agents_status"),
    )

    op.create_table(
        "log_entries",
        sa.Column("id", PortableBigInt, primary_key=True, autoincrement=True),
        sa.Column("agent_id", sa.BigInteger(), sa.ForeignKey("agents.id"), nullable=False),
        sa.Column("created_at", PortableTimestamp, nullable=False, server_default=sa.func.now()),
        sa.Column("session_id", sa.String()),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("summary", sa.String()),
        sa.Column("decisions", sa.String()),
        sa.Column("question", sa.String()),
        sa.Column("answer", sa.String()),
        sa.Column("visibility", sa.String(), nullable=False, server_default="project"),
        sa.Column("push_sha", sa.String()),
        sa.Column("ci_status", sa.String(), nullable=False, server_default="not_applicable"),
        sa.Column("ci_checked_at", PortableTimestamp),
        sa.CheckConstraint(f"visibility IN ({VISIBILITIES})", name="ck_log_visibility"),
        sa.CheckConstraint(f"ci_status IN ({CI_STATUSES})", name="ck_log_ci_status"),
    )

    op.create_table(
        "checkmarks",
        sa.Column("agent_id", sa.BigInteger(), sa.ForeignKey("agents.id"), primary_key=True),
        sa.Column("checkpoint_at", PortableTimestamp, nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("where_it_stopped", sa.String()),
        sa.Column("next_steps", PortableJSON),
        sa.Column("open_question", sa.String()),
        sa.Column(
            "log_entry_id",
            sa.BigInteger(),
            sa.ForeignKey("log_entries.id", name="fk_checkmarks_log_entry"),
        ),
        sa.Column("tests_status", sa.String(), nullable=False, server_default="unknown"),
        sa.Column("tested_at", PortableTimestamp),
        sa.Column("build_status", sa.String(), nullable=False, server_default="unknown"),
        sa.Column("built_at", PortableTimestamp),
        sa.CheckConstraint(f"status IN ({AGENT_STATUSES})", name="ck_checkmarks_status"),
        sa.CheckConstraint(f"tests_status IN ({GATE_STATUSES})", name="ck_checkmarks_tests"),
        sa.CheckConstraint(f"build_status IN ({GATE_STATUSES})", name="ck_checkmarks_build"),
    )

    op.create_table(
        "shared_context",
        sa.Column("key", sa.String(), primary_key=True),
        sa.Column("value", sa.String(), nullable=False),
        sa.Column("set_by_agent_id", sa.BigInteger(), sa.ForeignKey("agents.id")),
        sa.Column("updated_at", PortableTimestamp, nullable=False, server_default=sa.func.now()),
    )


def downgrade() -> None:
    op.drop_table("shared_context")
    op.drop_table("checkmarks")
    op.drop_table("log_entries")
    op.drop_table("agents")
    op.drop_table("projects")
